# Generated by Django 2.1.1 on 2018-10-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='geotable_id',
            field=models.IntegerField(null=True, verbose_name='百度地图geotable_id'),
        ),
        migrations.AddField(
            model_name='demand',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=22, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='demand',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=22, null=True, verbose_name='经度'),
        ),
    ]
