# Generated by Django 2.1.1 on 2018-10-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181012_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='poi_id',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='百度地图poi_id'),
        ),
        migrations.AddField(
            model_name='share',
            name='geotable_id',
            field=models.IntegerField(null=True, verbose_name='百度地图geotable_id'),
        ),
        migrations.AddField(
            model_name='share',
            name='poi_id',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='百度地图poi_id'),
        ),
    ]
