# Generated by Django 2.1.1 on 2018-10-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181015_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='head_pic',
            new_name='avatar',
        ),
    ]
