# Generated by Django 2.1.1 on 2018-10-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181015_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar', verbose_name='头像'),
        ),
    ]
