# Generated by Django 2.1.1 on 2018-10-29 03:03

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181015_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=common.utils.current_timestamp, null=True, verbose_name='创建时间')),
                ('updated_at', models.BigIntegerField(null=True, verbose_name='更新时间')),
                ('order_sn', models.CharField(max_length=128, verbose_name='订单号')),
                ('trade_no', models.CharField(max_length=128, verbose_name='交易号')),
                ('subject', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=128)),
                ('pay_method', models.SmallIntegerField(choices=[(1, '微信'), (2, '支付宝'), (3, '银联'), (4, '钱包')], verbose_name='交易方式')),
                ('payment_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际付款金额，用户实际需要付款的金额，包含了押金池抵扣金额')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单支付金额,不包含押金池抵扣金额')),
                ('pay_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '支付失败')], verbose_name='支付状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='实际支付金额，支付回调后写入')),
                ('pay_at', models.BigIntegerField(verbose_name='支付时间时间戳')),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_order', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.CASCADE, related_name='seller_order', to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Share', verbose_name='共享商品')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=common.utils.current_timestamp, null=True, verbose_name='创建时间')),
                ('updated_at', models.BigIntegerField(null=True, verbose_name='更新时间')),
                ('number', models.IntegerField(default=1, verbose_name='数量')),
                ('message', models.CharField(max_length=256, null=True, verbose_name='买家留言')),
                ('status', models.SmallIntegerField(choices=[(1, '待付款'), (2, '已发货'), (3, '待买家评价'), (4, '待卖家评价'), (5, '已关闭'), (6, '双方已评价'), (7, '带归还'), (7, '归还中')], verbose_name='订单状态')),
                ('trade_method', models.SmallIntegerField(choices=[(1, '买家自提')], verbose_name='交易方式')),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='租金')),
                ('rent_unit', models.SmallIntegerField(choices=[(1, '年'), (2, '月'), (3, '天')], verbose_name='租金时间单位')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金')),
                ('is_use_pool', models.SmallIntegerField(choices=[(1, '使用押金池'), (2, '不使用押金池')], default=1, verbose_name='是否使用押金池')),
                ('used_pool_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金池中所使用的押金')),
                ('start_at', models.BigIntegerField(null=True, verbose_name='开始时间')),
                ('end_at', models.BigIntegerField(null=True, verbose_name='结束时间')),
                ('delivery_at', models.BigIntegerField(null=True, verbose_name='发货时间')),
                ('receipt_at', models.BigIntegerField(null=True, verbose_name='收货时间')),
                ('return_at', models.BigIntegerField(null=True, verbose_name='归还时间')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Order', verbose_name='订单')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
