# Generated by Django 2.1.1 on 2018-10-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_orderinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_sn',
            new_name='order_no',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='rent_unit',
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_at',
            field=models.BigIntegerField(null=True, verbose_name='支付时间时间戳'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, '微信'), (2, '支付宝'), (3, '银联'), (4, '钱包')], null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '支付失败')], default=1, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '已发货'), (4, '待买家评价'), (5, '待卖家评价'), (6, '已关闭'), (7, '双方已评价'), (8, '待归还'), (9, '归还中')], default=1, verbose_name='订单状态'),
        ),
    ]
