# Generated by Django 2.1.1 on 2018-10-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181029_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='is_use_pool',
            field=models.BooleanField(choices=[(1, '使用押金池'), (2, '不使用押金池')], default=False, verbose_name='是否使用押金池'),
        ),
    ]
