# Generated by Django 2.1.1 on 2018-11-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_share_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '开启'), (-1, '关闭')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='实际付款金额，用户实际需要付款的金额，包含了押金池抵扣金额'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_info', to='api.Order', verbose_name='订单'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='order_info',
        ),
    ]
