# Generated by Django 2.1.1 on 2018-11-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181104_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='end_time',
            field=models.BigIntegerField(verbose_name='共享结束时间'),
        ),
        migrations.AlterField(
            model_name='share',
            name='start_time',
            field=models.BigIntegerField(verbose_name='共享开始时间'),
        ),
    ]
