# Generated by Django 2.1.3 on 2018-11-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181105_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='nickname',
        ),
    ]
