# Generated by Django 2.1.3 on 2018-11-13 03:03

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_userinfo_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.BigIntegerField(default=common.utils.current_timestamp, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.BigIntegerField(null=True, verbose_name='更新时间'),
        ),
    ]
