# Generated by Django 2.1.3 on 2018-12-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181113_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='enterprise',
        ),
        migrations.DeleteModel(
            name='Enterprise',
        ),
    ]
